name: Build and upload if new version
on:
  schedule:
    - cron: '0 0 * * *'
  workflow_dispatch:
  push:
    branches:
      - main

permissions:
  contents: write

jobs:
  build:
    runs-on: ubuntu-latest
    # env:
    #   SHOULD_BUILD: true

    steps:
      # See https://github.com/easimon/maximize-build-space/issues/45 and repository
      - name: Maximize build space
        run: |
          df -h
          sudo rm -rf /usr/share/dotnet
          sudo rm -rf /usr/local/lib/android
          sudo rm -rf /opt/ghc
          sudo rm -rf /opt/hostedtoolcache/CodeQL
          sudo docker image prune --all --force
          sudo docker builder prune -a
          df -h

      - uses: actions/checkout@v4
        name: Checkout
        with:
          fetch-depth: 0 # See https://github.com/actions/checkout/issues/1781
          fetch-tags: true

      - name: Get latest upstream tag
        run: echo "LATEST_UPSTREAM_TAG=$(./get_latest_upstream_tag.sh)" >> $GITHUB_ENV

      - name: Check if we should build
        run: |
          set +e # Allow commands to fail
          ./should_build.sh
          if [ $? -eq 0 ]; then
            echo "SHOULD_BUILD=true" >> $GITHUB_ENV
          else
            echo "SHOULD_BUILD=false" >> $GITHUB_ENV
          fi

      - name: Install Dependencies
        if: ${{ env.SHOULD_BUILD == 'true' }}
        run: sudo apt-get install -y libelf-dev

      - name: Setup ccache
        if: ${{ env.SHOULD_BUILD == 'true' }}
        uses:  hendrikmuhs/ccache-action@v1
        with:
          key: linux-${{ github.run_id }}
          restore-keys: linux

      - name: Clone Linux Kernel
        if: ${{ env.SHOULD_BUILD == 'true' }}
        run: git clone --depth 1 --branch $(./get_latest_upstream_tag.sh) https://github.com/torvalds/linux linux

      - name: Build Linux Kernel
        if: ${{ env.SHOULD_BUILD == 'true' }}
        run: |
          ./get_config.sh
          mv .config linux/.config
          cd linux
          make olddefconfig # Apply new default values for new config options
          export PATH="/usr/lib/ccache:/usr/local/opt/ccache/libexec:$PATH"
          make -j $(nproc)

      - name: Package Linux Kernel
        if: ${{ env.SHOULD_BUILD == 'true' }}
        run: |
          ./package.sh
      
      - name: Upload Artifact
        if: ${{ env.SHOULD_BUILD == 'true' }}
        uses: actions/upload-artifact@v4
        with:
          name: linux-kernel
          path: linuxRC.tar.gz

      - name: Create release
        if: ${{ env.SHOULD_BUILD == 'true' }}
        uses: ncipollo/release-action@v1
        with:
          artifacts: linuxRC.tar.gz
          tag: ${{ env.LATEST_UPSTREAM_TAG }}

      - name: Keep the repository active
        uses: gautamkrishnar/keepalive-workflow@v2
