name: Build and Upload Artifact
on:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4

      - name: Install Dependencies
        run: sudo apt-get install -y libelf-dev

      - name: Setup ccache
        uses:  hendrikmuhs/ccache-action@v1
        with:
          key: linux-${{ github.run_id }}
          restore-keys: linux

      - name: Clone Linux Kernel
        run: git clone --depth 1 https://github.com/torvalds/linux linux

      - name: Build Linux Kernel
        run: |
          cd linux
          make defconfig
          export PATH="/usr/lib/ccache:/usr/local/opt/ccache/libexec:$PATH"
          make -j $(nproc)

      - name: Package Linux Kernel
        run: |
          ./package.sh
      
      - name: Upload Artifact
        uses: actions/upload-artifact@v4
        with:
          name: linux-kernel
          path: linuxAB.tar.gz
