name: Build and Upload Artifact
on:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4

      - name: Setup ccache
        uses: iTrooz/ccache-action@main
        with:
          cleanUnused: true

      - run: ccache gcc -c main.c
