name: Build and Upload Artifact
on:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Upload artifact
        uses: iTrooz/upload-artifact@main
        with:
          name: my-artifact
          path: /bin/ls